---
title: "Module 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# {.tabset}

## Subsetting and sorting 

```{r}
set.seed(13435)
X <- data.frame("var1"=sample(1:5), 
                "var2"=sample(6:10),
                "var3"=sample(11:15))

X <- X[sample(1:5), ]
X$var2[c(1,3)] = NA
X


X[1,]
X[,"var1"] # quotes!
X[c(1,2), "var1"]


# Logicals
X[X$var1 <= 3 & X$var3 > 11, ]
X[X$var1 <= 3 | X$var3 > 15, ]

# which() ignores NAs
X[which(X$var2 > 8),] 

# Sorting
sort(X$var1, decreasing = T)
sort(X$var2, decreasing = T, na.last = T)

# Ordering
X[order(X$var1), ]
X[order(X$var1, X$var3), ]

# Adding rows and columns
X$var4 <- rnorm(5)
X
```


## Creating new variables 
```{r}
# Creating sequences
s1 <- seq(1,10,by=2); s1
s2 <- seq(1,10, length=3); s2
x <- c(1,3,5,6,7,10)
seq(along=x)
```

```{r}
# Subsetting variables
restData <- read.csv("restaurants.csv")
restData$nearMe <- restData$neighborhood %in% c("Roland Park", 
                                                "Homeland")
table(restData$nearMe)

# Creating BINARY variables
restData$zipWrong <- ifelse(restData$zipCode < 0, T, F)
table(restData$zipWrong)
table(restData$zipWrong, restData$zipCode < 0)

# Creating CATEGORICAL variables
restData$zipGroups <- cut(restData$zipCode,
                          breaks = quantile(restData$zipCode))
table(restData$zipGroups, restData$zipCode)

# Easier cutting
library(Hmisc)
restData$zipGroups <- cut2(restData$zipCode, g=4) # factor! 
class(restData$zipGroups) 
table(restData$zipGroups)


# Creating FACTOR variables
restData$zcf <- factor(restData$zipCode)
restData$zcf[1:5]

yesno <- factor(sample(c("yes", "no"), 10, replace = T)); yesno # no/yes
yesno <- relevel(yesno, ref="yes"); yesno # yes/no 

# MUTATE
library(dplyr)
restData <- mutate(restData, zipGroups=cut2(zipCode, g=4))
table(restData$zipGroups)

```

## Summarizing data

```{r}
# Quantiles of quantitative variables
quantile(restData$councilDistrict, na.rm = T)
quantile(restData$councilDistrict, probs = c(.25, .75, .9))

# Make table
table(restData$zipCode, useNA = "ifany")

# Check for missing values
sum(is.na(restData$councilDistrict))
any(is.na(restData$councilDistrict))
all(restData$zipCode > 0)
colSums(is.na(restData))
all(colSums(is.na(restData)) == 0)

# Values with specific characteristics
table(restData$zipCode %in% c("21212"))
table(restData$zipCode %in% c("21212", "21213"))
head(restData[restData$zipCode %in% c("21212", "21213"), ])

# Cross tabs
data("UCBAdmissions")
DF <- as.data.frame(UCBAdmissions)
summary(DF)

xt <- xtabs(Freq ~ Gender + Admit, data=DF); xt

# Flat tables
warpbreaks$replicate <- rep(1:9, len=54)
xt <- xtabs(breaks ~ .,data=warpbreaks); xt
head(ftable(xt))
```

## Reshape data

```{r}
library(reshape2)

# Melting data frames
mtcars$carname <- rownames(mtcars)
carMelt <- melt(mtcars, 
                id = c("carname", "gear", "cyl"),
                measure.vars = c("mpg", "hp"))
head(carMelt)
tail(carMelt)

# Reshape
cylData <- dcast(carMelt, cyl ~ variable)
cylData

cylData <- dcast(carMelt, cyl ~ variable, mean)
cylData
```

```{r}
head(InsectSprays)

tapply(InsectSprays$count, InsectSprays$spray, sum)

spIns <- split(InsectSprays$count, InsectSprays$spray)
spIns # list!

sprCount <- lapply(spIns, sum)
sprCount

unlist(sprCount)
sapply(spIns, sum)
```

```{r}
library(plyr)

ddply(InsectSprays, .(spray), summarize, sum=sum(count))
spraySums <- ddply(InsectSprays, .(spray), summarize, 
                   sum=ave(count, FUN=sum))
dim(spraySums)
```

## dplyr

```{r}
library(dplyr)

chicago <- readRDS("chicago.rds")
dim(chicago)
str(chicago)
names(chicago)

# select() columns
head(select(chicago, city:dptp))

head(select(chicago, -(city:dptp)))

# filter() rows
chic.f <- filter(chicago, pm25tmean2 > 30)
head(chic.f)

chic.f <- filter(chicago, pm25tmean2 > 30 & tmpd > 80)
chic.f

# arrange() rows by values in a column
chicago <- arrange(chicago, date)
head(chicago)

chicago <- arrange(chicago, desc(date))
head(chicago)

# rename() columns
chicago <- dplyr::rename(chicago, pm25 = pm25tmean2, 
                  dewpoint = dptp)
head(chicago)

# mutate() existing variables or create new ones
chicago <- mutate(chicago, pm25dtrend=pm25-mean(pm25, na.rm=T))
head(chicago)

chicago <- mutate(chicago, 
                  tempcat = factor(1 * (tmpd > 80), 
                                   labels = c("cold", "hot")))
head(chicago)

# group_by()
hotcold <- group_by(chicago, tempcat)
head(hotcold)

summarize(hotcold, pm25 = mean(pm25, na.rm=T), 
          o3 = max(o3tmean2))
```

## Merging data

```{r}
reviews <- read.csv("reviews.csv")
solutions <- read.csv("solutions.csv")

head(reviews,2)
head(solutions,2)

names(reviews)
names(solutions)

# x, y, by, by.x, by.y, all
mergedData <- merge(reviews, solutions,
                    by.x = "solution_id", 
                    by.y = "id",
                    all = T)

head(mergedData)

```

